// apps/frontend-app/src/pages/room/components/QuestionPanel.tsx
import { useCallback, useEffect, useState } from '@lynx-js/react'
import { ApiRequestError, skipQuestion, submitAnswer } from '@lejv-party/api-client'
import type { GameStatePublic, PlayerState } from '@lejv-party/domain'
import { Button, Input } from '@lynx-js/lynx-ui'

import { useNow } from '../../../hooks/useNow.js'
import { Leaderboard } from './Leaderboard.js'

type Props = {
  roomId: string
  playerId: string
  hostId: string
  players: PlayerState[]
  game: GameStatePublic
}

export function QuestionPanel(props: Props) {
  const isHost = props.playerId === props.hostId
  const now = useNow(true)
  const current = props.game.current
  const remainingSec = Math.max(
    0,
    Math.ceil(((current?.deadlineAt ?? now) - now) / 1000),
  )

  const [answer, setAnswer] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [selfAnswered, setSelfAnswered] = useState(false)
  const [selfCorrect, setSelfCorrect] = useState<boolean | null>(null)
  const [feedback, setFeedback] = useState<string | null>(null)

  useEffect(() => {
    setAnswer('')
    setSubmitting(false)
    setSelfAnswered(false)
    setSelfCorrect(null)
    setFeedback(null)
  }, [props.game.questionIndex])

  const onSubmit = useCallback(() => {
    const trimmed = answer.trim()
    if (!trimmed || submitting || selfAnswered) return
    setSubmitting(true)
    setFeedback(null)
    void submitAnswer(props.roomId, props.playerId, trimmed)
      .then((body) => {
        setSelfAnswered(true)
        setSelfCorrect(body.correct)
        setFeedback(body.correct ? '答对了！' : '答错了')
      })
      .catch((err: unknown) => {
        if (err instanceof ApiRequestError) {
          if (err.body.error === 'ALREADY_ANSWERED') {
            setSelfAnswered(true)
            setFeedback('你已作答')
          } else if (err.body.error === 'NOT_IN_QUESTION') {
            setFeedback('本题已结束')
          } else {
            setFeedback('提交失败')
          }
        } else {
          setFeedback('提交失败')
        }
      })
      .finally(() => setSubmitting(false))
  }, [answer, props.playerId, props.roomId, selfAnswered, submitting])

  const onSkip = useCallback(() => {
    if (!isHost) return
    void skipQuestion(props.roomId, props.playerId).catch(() => {
      // best-effort
    })
  }, [isHost, props.playerId, props.roomId])

  const submitDisabled =
    selfAnswered || submitting || !answer.trim()

  return (
    <view className="stack">
      <view className="card">
        <view className="card__header">
          <text className="muted">第 {props.game.questionIndex} 题</text>
          <text className={remainingSec <= 10 ? 'countdown countdown--warn' : 'countdown'}>
            {remainingSec}s
          </text>
        </view>
        <view className="quote">
          <text className="quote__text">
            “{current?.translation ?? '…'}”
          </text>
        </view>

        <view className="field">
          <Input
            className="input"
            placeholder={selfAnswered ? '你已作答' : '输入歌名'}
            maxLength={64}
            readonly={selfAnswered || submitting}
            value={answer}
            onInput={setAnswer}
          />
        </view>
        <Button
          className="btn"
          disabled={submitDisabled}
          onClick={onSubmit}
        >
          <text className="btn__text">
            {submitting ? '提交中…' : '抢答'}
          </text>
        </Button>
        {feedback ? (
          <text className={selfCorrect ? 'ok' : 'error'}>{feedback}</text>
        ) : null}

        <text className="muted">
          已作答：{current?.answeredCount ?? 0} / {props.players.length}
        </text>

        {isHost ? (
          <Button className="btn btn--secondary" onClick={onSkip}>
            <text className="btn__text">下一题（跳过）</text>
          </Button>
        ) : null}
      </view>

      <Leaderboard
        players={props.players}
        scores={props.game.scores}
        hostId={props.hostId}
        selfId={props.playerId}
      />
    </view>
  )
}

// apps/frontend-web/src/components/room/QuestionPanel.vue
<script setup lang="ts">
import { skipQuestion } from '@lejv-party/api-client'
import type { GameStatePublic, PlayerState } from '@lejv-party/domain'
import { computed } from 'vue'

import { useNow } from '@/composables/useNow'

import BuzzerForm from './BuzzerForm.vue'
import RoomLeaderboard from './RoomLeaderboard.vue'

const props = defineProps<{
  roomId: string
  playerId: string
  hostId: string
  players: PlayerState[]
  game: GameStatePublic
}>()

const isHost = computed(() => props.playerId === props.hostId)
const now = useNow(true)

const current = computed(() => props.game.current)
const remainingSec = computed(() => {
  const deadlineAt = current.value?.deadlineAt ?? now.value
  return Math.max(0, Math.ceil((deadlineAt - now.value) / 1000))
})

async function onSkip() {
  if (!isHost.value) return
  try {
    await skipQuestion(props.roomId, props.playerId)
  } catch {
    // best-effort
  }
}
</script>

<template>
  <div class="grid w-full grid-cols-1 gap-4 lg:grid-cols-3">
    <section
      class="rounded-lg border border-zinc-200 bg-white p-6 shadow-sm dark:border-zinc-800 dark:bg-zinc-900 lg:col-span-2"
    >
      <div class="mb-4 flex items-center justify-between">
        <p class="text-sm text-zinc-500 dark:text-zinc-400">第 {{ game.questionIndex }} 题</p>
        <p
          class="font-mono text-4xl font-bold"
          :class="
            remainingSec <= 10
              ? 'text-red-600 dark:text-red-400'
              : 'text-zinc-900 dark:text-zinc-50'
          "
          aria-live="polite"
        >
          {{ remainingSec }}s
        </p>
      </div>

      <blockquote class="mb-6 rounded-md bg-zinc-50 p-6 dark:bg-zinc-800">
        <p class="text-2xl font-medium italic leading-relaxed text-zinc-900 dark:text-zinc-50">
          &ldquo;{{ current?.translation ?? '…' }}&rdquo;
        </p>
      </blockquote>

      <BuzzerForm
        :key="game.questionIndex"
        :room-id="roomId"
        :player-id="playerId"
      />

      <p class="mt-4 text-xs text-zinc-500 dark:text-zinc-400">
        已作答：{{ current?.answeredCount ?? 0 }} / {{ players.length }}
      </p>

      <button
        v-if="isHost"
        type="button"
        class="mt-4 rounded-md border border-zinc-300 px-3 py-1.5 text-xs text-zinc-600 hover:bg-zinc-100 dark:border-zinc-700 dark:text-zinc-400 dark:hover:bg-zinc-800"
        @click="onSkip"
      >
        下一题（跳过）
      </button>
    </section>

    <section
      class="rounded-lg border border-zinc-200 bg-white p-6 shadow-sm dark:border-zinc-800 dark:bg-zinc-900"
    >
      <RoomLeaderboard
        :players="players"
        :scores="game.scores"
        :host-id="hostId"
        :self-id="playerId"
      />
    </section>
  </div>
</template>
