// apps/frontend-app/src/pages/room/components/RevealPanel.tsx
import type { GameStatePublic, PlayerState } from '@lejv-party/domain'

import { useNow } from '../../../hooks/useNow.js'
import { Leaderboard } from './Leaderboard.js'

type Props = {
  players: PlayerState[]
  hostId: string
  playerId: string
  game: GameStatePublic
}

export function RevealPanel(props: Props) {
  const now = useNow(true)
  const current = props.game.current
  const scorer = current?.scorer
  const scorerName = scorer
    ? (props.players.find((p) => p.id === scorer)?.nickname ?? '匿名')
    : null

  const nextAt = current?.revealAt
  const nextInSec =
    nextAt === undefined ? null : Math.max(0, Math.ceil((nextAt - now) / 1000))

  return (
    <view className="stack">
      <view className="card">
        <text className="muted">第 {props.game.questionIndex} 题 · 答案揭晓</text>
        <text className="title-dark">{current?.title ?? '—'}</text>
        <text className="muted">{current?.artist ?? ''}</text>
        <view className="quote">
          {scorerName ? (
            <text className="ok">🎉 {scorerName} 抢答正确，+1 分</text>
          ) : (
            <text className="muted">本题无人答对</text>
          )}
        </view>
        {nextInSec !== null ? (
          <text className="muted">{nextInSec} 秒后进入下一题…</text>
        ) : null}
      </view>

      <Leaderboard
        players={props.players}
        scores={props.game.scores}
        hostId={props.hostId}
        selfId={props.playerId}
        highlightScorer={current?.scorer ?? null}
      />
    </view>
  )
}

// apps/frontend-web/src/components/room/RevealPanel.vue
<script setup lang="ts">
import type { GameStatePublic, PlayerState } from '@lejv-party/domain'
import { computed } from 'vue'

import { useNow } from '@/composables/useNow'

import RoomLeaderboard from './RoomLeaderboard.vue'

const props = defineProps<{
  players: PlayerState[]
  hostId: string
  playerId: string
  game: GameStatePublic
}>()

const now = useNow(true)
const current = computed(() => props.game.current)

const scorerName = computed(() => {
  const scorer = current.value?.scorer
  if (!scorer) return null
  return props.players.find((p) => p.id === scorer)?.nickname ?? '匿名'
})

const nextInSec = computed(() => {
  const nextAt = current.value?.revealAt
  if (nextAt === undefined) return null
  return Math.max(0, Math.ceil((nextAt - now.value) / 1000))
})
</script>

<template>
  <div class="grid w-full grid-cols-1 gap-4 lg:grid-cols-3">
    <section
      class="rounded-lg border border-zinc-200 bg-white p-6 shadow-sm dark:border-zinc-800 dark:bg-zinc-900 lg:col-span-2"
    >
      <p class="mb-2 text-sm text-zinc-500 dark:text-zinc-400">
        第 {{ game.questionIndex }} 题 · 答案揭晓
      </p>
      <p class="text-3xl font-bold text-zinc-900 dark:text-zinc-50">
        {{ current?.title ?? '—' }}
      </p>
      <p class="mt-1 text-base text-zinc-600 dark:text-zinc-400">
        {{ current?.artist ?? '' }}
      </p>

      <div class="mt-6 rounded-md bg-zinc-50 p-4 dark:bg-zinc-800">
        <p
          v-if="scorerName"
          class="text-base text-emerald-700 dark:text-emerald-400"
        >
          <span aria-hidden>🎉</span> {{ scorerName }} 抢答正确，+1 分
        </p>
        <p v-else class="text-base text-zinc-600 dark:text-zinc-300">本题无人答对</p>
      </div>

      <p
        v-if="nextInSec !== null"
        class="mt-6 text-center text-sm text-zinc-500 dark:text-zinc-400"
      >
        {{ nextInSec }} 秒后进入下一题…
      </p>
    </section>

    <section
      class="rounded-lg border border-zinc-200 bg-white p-6 shadow-sm dark:border-zinc-800 dark:bg-zinc-900"
    >
      <RoomLeaderboard
        :players="players"
        :scores="game.scores"
        :host-id="hostId"
        :self-id="playerId"
        :highlight-scorer="current?.scorer ?? null"
      />
    </section>
  </div>
</template>
